server:
  port: 8060
  servlet:
    context-path: /mall

spring:
  redis:
    port: 6379
    database: 4
    jedis:
      pool:
        max-active: 8
        min-idle: 0

  datasource:
    url: jdbc:mysql://localhost:3306/mmall?useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: agytorudhcv11


  session:
    store-type: redis


mybatis:
  mapper-locations: classpath*:mappers/*.xml
