server:
  port: 8060
  servlet:
    context-path: /mall

spring:
  redis:
    port: 6379
    database: 4
    jedis:
      pool:
        max-active: 8
        min-idle: 0

  datasource:
    url: jdbc:mysql://localhost:3306/mmall?useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: agytorudhcv11


  session:
    store-type: redis
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB


mybatis:
  mapper-locations: classpath*:mappers/*.xml



bsb:
  mall:
    ftp:
      serverIp: xiyoumobilebackres.xyz
      serverPort: 21
      user: zeng
      password: agytorudhcv11
      serverHttpPrefix: http://xiyoumobilebackres.xyz/
    aliPay:
      callBackUrl: http://9rx295.natappfree.cc/mall/order/aliPayCallBack
#      callBackUrl: http://www.xiyoumobileback.club:8080/mall/order/aliPayCallBack